### PR TITLE
UsedTiles

### PR DESCRIPTION
**Pull request by MatLukac**
fully implemented UsedTiles class

### CODE REVIEW

**Comment by KristianAndrascik** [comment]
Your performance is commendable. Your work is of a high standard and has been executed with great skill. Thank you for your dedication and hard work in achieving excellent results.

**Review by KristianAndrascik — CHANGES_REQUESTED** [review]
The file named '.idea' should be present here?

**Comment by MatLukac** [comment]
> The file named '.idea' should be present here?

**Comment by MatLukac** [comment]
> The file named '.idea' should be present here?

fixed, .idea directory deleted. ur welcome

**Review by KristianAndrascik — APPROVED** [review]

**Pull request merged**
